### ISSUE TITLE
FR: Shrink scene selection lights to make mouse target for hitting outside knob bigger

### ISSUE THREAD

**Issue by fractalgee** [partvishegy/Noumenal#1]
Hi, HUB is a cool module. Just the mouse target for moving the outside scene selection level knob is rather small due to the huge scene light in the middle. If patch is busy this makes it hard to hit the knob to tweak, without it being mapped to a target that is easy to hit with the mouse to manipulate. Could those lights be shrunk a bit so the knob surface itself is bigger to make them easier to dial in, pretty please?

**Comment by partvishegy** [comment]
Hi, thank you for the feedback! I do want to keep it a strong visual element, but I aggree that sometimes it is hard to hit the right part of the knob, when zoomed out. So I will experiment with smaller sizes for the path selection knobs to find a better ballance bw looks and usability.

**Comment by partvishegy** [comment]
Hi, a new version (2.0.1) of HUB is out. I shrank the the path selector switches by about 20%. @fractalgee I would love to know if you find this change noticeable or the original problem is still present!

**Comment by fractalgee** [comment]
Much better! Thanks a bunch, makes accidental clicks on scene light much less an issue.
