### ISSUE TITLE
Could we get an arm64 Mac build?

### ISSUE THREAD

**Issue by fractalgee** [partvishegy/Noumenal#2]
Given the fact that the arm64 Mac version of VCV Rack 2 is out of beta and the official toolchain supports automatic builds for arm64 on top of x64 for mac, could you please get an arm build ready to submit to the library? It is the only thing I am still missing to switch to the native arm64 version of Rack for good. Thanks in advance!

**Comment by partvishegy** [comment]
Hi, I'll look into it on tuesday!

fractalgee ***@***.***> ezt írta (időpont: 2023. nov. 19.,
Vas 15:02):

**Comment by fractalgee** [comment]
I don't want to be pushy, but how are things going?

**Comment by partvishegy** [comment]
Hi, sorry for the long wait, I have some trouble building the plugin toolchain for Mac. Currently I can't generate the proper version of sdk needed for the build (MacOSX11.1.sdk.tar.xz). I asked for advice in the toolchain's git issues.

**Comment by fractalgee** [comment]
I can't help with the 11.1 SDK, as I have no access to a mac that has support for 11,1 so all I could give you is the 14.2 SDK. This is of course assuming that 11.1 is the minimum version and any higher version will do as well. 11.1 is ancient so no idea who would still be able to generate one for 11.1....

**Comment by fractalgee** [comment]
You need Xcode 12.4 to generate it. It's a .xip file so you need to run (on Linux and you copied the 12.4 Xcode.xip to osxcross dir) 

```
./tools/gen_sdk_package_pbzx.sh Xcode.xip
```

in the osxcross directory. 

I just tested it and it works fine. If all else fails I can give you my packaged 11.1 SDK tar.xz file, it's just over 55MB in size.

**Comment by partvishegy** [comment]
Thank you, it worked! I'm building the toolchain now, hopefully without further issues!

**Comment by partvishegy** [comment]
Finally finished the build, you can find it in the [releases](https://github.com/partvishegy/Noumenal/releases/tag/v2.0.1). Please let me know if it works properly on mac-arm64, I could only test it on linux and windows.

**Comment by fractalgee** [comment]
Works perfectly! Thanks!

**Comment by fractalgee** [comment]
Kicked the tires a lot more, no issues to be found, so seems ready to submit to library. That would be great. One less 'no arm64 support' plugins there :)

**Comment by partvishegy** [comment]
It's up!

**Comment by fractalgee** [comment]
yep, saw it, thanks a bunch!
